workflow:
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /-draft$/
      when: never
    - if: $CI_PIPELINE_SOURCE == "push"
      when: always
stages:
   - build
   - test

default:
  before_script:
      - python3 --version ; pip --version
      - pip install virtualenv
      - virtualenv venv
      - source venv/bin/activate
      - pip install -r requirements.txt

lint_code:
  stage: build
  tags:
    - autoscale
  script:
    - flake8 . --count --select=E9,F63,F7 --show-source --statistics --exit-zero
    - flake8 . --count --max-complexity=10 --max-line-length=127 --statistics --exit-zero

run_tests:
  stage: test
  tags:
    - autoscale
  script:
    - pip install .
    - pytest
  artifacts:
    expire_in: "5 mins"


